// <auto-generated />
namespace MVC_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editmodelaccview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editmodelaccview));
        
        string IMigrationMetadata.Id
        {
            get { return "202012140009572_editmodelaccview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
