// <auto-generated />
namespace MVC_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_view_alphabetical : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_view_alphabetical));
        
        string IMigrationMetadata.Id
        {
            get { return "202012131455391_added_view_alphabetical"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
